### PR TITLE
Changed deploy to use Cake.Git & KuduSync

### PR DESCRIPTION
**Pull request by devlead**
Changed from shelling out to git to using the Cake.Git addin and Kudu Sync to sync output folder with publish repo.

To work this needs 2 new environment variables added to AppVeyor

| Variable                  | Description          | Example                                               |
|----------------------|--------------------|------------------------------------------|
| git_deploy_remote  | Where to publish| https://github.com/gep13/gep13.git  |
| git_deploy_branch | Which branch to publish to | gh-pages |

### CODE REVIEW

**Comment by gep13** [comment]
Thank you very much for doing this!  Didn't know that you could use Kudu in isolation like this!

**Comment by gep13** [comment]
@daveaglick might be interested in taking a look at this.

**Comment by devlead** [comment]
@gep13 this could also be the path forward for the @cake-build/website, as we could build It anywhere and based on different env vars per branch deciding on where to publish.

**Comment by gep13** [comment]
@devlead that is very true.

**Comment by devlead** [comment]
@gep13 this is a nice feature too
image

**Comment by gep13** [comment]
@devlead yes, I spotted that little nugget that you added there 😄

**Comment by daveaglick** [comment]
AppVeyor 4 Lyfe

**Pull request merged**
