### PR TITLE
Updated my attendance count

### PR DESCRIPTION
**Pull request by NathanGloyn**

### CODE REVIEW

**Comment by gep13** [comment]
@NathanGloyn can you rebase this on latest source? You seem to have some extra commits that aren't needed.

**Comment by gep13** [comment]
23 eh! You will be at the top soon :smile:

**Comment by NathanGloyn** [comment]
I doubt it Liam has updated his count which I think would put him above me and I think Dave has attended a couple as well

**Comment by gep13** [comment]
@NathanGloyn ping

**Comment by gep13** [comment]
@NathanGloyn I am going to go ahead and close this PR.  If you are still interested in updating your attendance, the new file is here:

https://github.com/gep13/gep13/blob/master/input/blog/ddd-attendance-leaderboard-where-do-you-rank.md

Thanks!

**Pull request closed without merging**
